// uso temporario

export const Names = [
    'Arthur',
    'Théo',
    'Heitor',
    'Gael',
    'Davi',
    'Bernardo',
   'Gabriel',
    'Ravi',
    'Noah',
    'Samuel',
   'Pedro',
    'Benício',
    'Benjamin',
    'Matheus',
    'Isaac',
    'Anthony',
   'Joaquim',
   'Lucas',
    'Lorenzo',
    'Rafael',
    'Nicolas',
    'Henrique',
    'Murilo',
    'João Miguel',
    'Lucca',
    'Guilherme',
    'Henry',
    'Bryan',
    'Gustavo',
    'Felipe',
    'Pietro',
    'Levi',
    'Daniel',
    'JoãoPedro',
    'Bento',
    'Vicente',
    'Leonardo',
    'Caleb',
    'Pedro Henrique',
    'Matteo',
    'Enzo Gabriel',
    'João',
    'Antônio',
    'Emanuel',
    'Enzo',
    'Davi Lucca',
    'Caio',
    'Eduardo',
    'João Lucas',
    'Thomas',
    'Cauã',
   'Vitor',
    'José',
    'Enrico',
    'Augusto',
    'João Gabriel',
    'Francisco',
    'Otávio',
    'Yuri',
    'Valentim',
    'Vinícius',
    'Davi Lucas',
    'Rael',
    'Mathias',
    'Theodoro',
    'Yan',
    'João Guilherme',
    'Nathan',
    'Arthur Miguel',
    'Oliver',
    'Anthony Gabriel',
    'Ryan',
    'Luiz Miguel',
    'Erick',
    'João Vitor',
    'Luan',
    'Thiago',
    'Apollo',
    'Ícaro',
    'Breno',
    'Arthur Gabriel',
    'Derick',
   'Kauê',
    'Martin',
    'Luiz Felipe',
   'Raul',
    'Liam',
   'Davi Miguel',
    'Pedro Lucas',
    'José Miguel',
   'Josué',
    'Pedro Miguel',
  'Micael',
   'Yago',
  'Dominic',
   'Vitor Hugo',
    'Luiz Henrique',
    'Estevão',
    'Davi Luiz'
]